name: Build Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli
        
      - name: Install Dashboard Dependencies
        run: |
          cd dashboard
          npm install
          npm run build
          
      - name: Build Tauri App
        run: |
          cd browser-core
          cargo tauri build
          
      - name: Upload Windows Installers
        uses: actions/upload-artifact@v4
        with:
          name: windows-installers
          path: |
            browser-core/target/release/bundle/msi/*.msi
            browser-core/target/release/bundle/nsis/*.exe
          
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli
        
      - name: Install Dashboard Dependencies
        run: |
          cd dashboard
          npm install
          npm run build
          
      - name: Build Tauri App
        run: |
          cd browser-core
          cargo tauri build
          
      - name: Upload macOS Installer
        uses: actions/upload-artifact@v4
        with:
          name: macos-installer
          path: |
            browser-core/target/release/bundle/dmg/*.dmg
            
  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-installers
          path: ./installers
          
      - name: Download macOS Artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-installer
          path: ./installers
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./installers/*
          generate_release_notes: true
          draft: false
          prerelease: false 